return {
  'folke/snacks.nvim',
  priority = 1000,
  lazy = false,
  opts = {
    bigfile = { enabled = true },
    dashboard = { enabled = false },
    debug = { enabled = false },
    dim = {enabled = true},
    explorer = {},
    git = { enabled = false },
    image = { enabled = true },
    indent = { enabled = false },
    input = { enabled = true },
    lazygit = { enabled = false },
    notifier = { enabled = true },
    notify = { enabled = true },
    picker = { enabled = true, },
    quickfile = { enabled = false },
    scope = { enabled = true, treesitter = { enable = true, } },
    scratch = { enabled = false },
    scrollbar = { enabled = false },
    statuscolumn = { enabled = true },
    terminal = { enabled = false },
    toggle = { enabled = false },
    words = { enabled = false },
    zen = { enabled = false }
  },
  keys = {
    { '<leader>b', function() Snacks.picker.buffers({ layout = { preset = 'vscode' } }) end },
    { '<leader>x', function() Snacks.picker.explorer() end },
    { '<leader>f', function() Snacks.picker.files({ layout = {} }) end },
    { '<leader>/', function() Snacks.picker.grep({ layout = { preset = 'vertical' } }) end },
    { '<leader>u', function() Snacks.picker.undo({ layout = { preset = 'vertical' } }) end },
  },
}
